package edu.poly.common;

public enum PageType {
//	PAGE ADMIN
	USER_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	VIDEO_MANAGEMENT_PAGE,
	
//	PAGE USER
	SITES_HOME_PAGE,
	SITES_FAVOURITES_PAGE,
	SITES_VIEW_HISTORY_PAGE,
	SITES_DETAIL_PAGE,
	SITES_CONTACT_PAGE,
	SITES_LOGIN_PAGE,
	SITES_REGISTRATION_PAGE,
	SITES_CHANGE_PASSWORD_PAGE,
	SITES_CONFIRM_PAGE,
	SITES_FORGOT_PASSWORD_PAGE,
	SITES_EDIT_PROFILE_PAGE,
	SITES_SEARCH_VIDEOS_PAGE,
}
